config/routes.rb
require 'route_constraints/oauth_constraint'

Rails.application.routes.draw do

  root 'welcome#index'

  get 'redirect', to: "redirects#handle", constraints: OAuthConstraint.new
  get 'redirect', to: "redirects#error"

  put '/update', to: "users#update"

  get 'profile', to: "profiles#show"

  get 'users/:github_id/languages', to: "users#languages", defaults: { format: :js }
  get 'users/:github_id/repositories', to: "users#repositories", defaults: { format: :js }
  get 'repositories/:id/languages', to: "repositories#languages", defaults: { format: :js }
  get 'repositories/:id/readme', to: "repositories#analyze_readme", defaults: { format: :js }
  get 'repositories/:id/language', to: "repositories#analyze_language", defaults: { format: :js }

  get 'recommend', to: "recommendations#recommend", defaults: { format: :js }

end

app/models/repository.rb
class Repository < ActiveRecord::Base
  ## ATTRIBUTES
  # id: GitHub unique identifier for this repository
  # watchers: the number of users that starred this repo
  # pushed_at: last date of commit to master
  # readme_url: url to the raw readme
  # readme_text: text of the readme
  # languages: hash of the language breakdown for the repository
  # is_private: boolean of whether the repo is private or not

  validates :readme_url, presence: true
  belongs_to :user

  def language_breakdown
    total = language_total
    languages.to_a.map { |lang| [lang[0], (lang[1].to_i / language_total).round(2)] }
  end

  def language_total
    language_values.inject(0.0) { |sum, next_value| sum += next_value }
  end

  def language_values
    languages.values.map { |value| value.to_i }
  end

  def score(user)
    readme_score = Recommender::RecommenderActions.analyze_readme(user, nil, self)
    language_score = Recommender::RecommenderActions.analyze_language(user, nil, self)
    star_score = Recommender::RecommenderActions.analyze_stars(watchers)
    commit_score = Recommender::RecommenderActions.analyze_commit_date(pushed_at)
    readme_score + language_score + star_score + commit_score
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  ## ATTRIBUTES
  # login: GitHub login
  # access_token: GitHub OAuth access token
  # github_id: GitHub unique identifier for account
  # keyword_one: most desirable keyword
  # ....
  # keyword_five: least desirable keyword
  # language_breakdown: array of percentages for each language
  # avatar_url: link to the github avatar

  serialize(:language_breakdown, Array)
  has_many :repositories

  def keywords
    [ keyword_one,
      keyword_two,
      keyword_three,
      keyword_four,
      keyword_five ]
  end

  def has_all_keywords?
    keywords.compact.count.eql?(5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Include the users helper in our application controller
  # in order to get access to user authentication methods
  include UsersHelper
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def recommend
    repositories = Repository.limit(50).order("RANDOM()")
    @top_five = Recommender::Support::Repository.score(repositories, current_user)
  end
end

app/controllers/redirects_controller.rb
require 'net/https'
require 'net/http'
require 'open-uri'

class RedirectsController < ApplicationController
  def handle
    access_token = authenticate_via_github
    if access_token.nil?
      render :error
    else
      user = Octokit::Client.new(access_token: access_token).user
      sign_in_or_sign_up_user(user, access_token)
      redirect_to "/profile"
    end
  end

  def error

  end

  protected
  # send a post request to the oauth access token url, and then parse the request body
  def authenticate_via_github
    uri = "https://github.com/login/oauth/access_token"
    body = Recommender::Support::Request.makeSecureGet(uri, post_params)
    get_access_token(body)
  end

  # parse the request body in order to get the access token
  def get_access_token(body)
    body.split('&')[0].split('=')[1]
  end

  # parameters that will be posted to github's oauth url to get an access token
  def post_params
    { client_id: ENV["client_id"],
      client_secret: ENV["client_secret"],
      code: params[:code] }
  end

  # parameters that will be used to create a new user
  def user_params(github_result, access_token)
    { login: github_result.login,
      github_id: github_result.id,
      avatar_url: github_result.avatar_url,
      access_token: access_token }
  end

  # using the github API result we obtained through 'user = Octokit::Client.new(access_token: access_token).user',
  # we either try to find a user that we have already created or create a new one, and sign them in.
  def sign_in_or_sign_up_user(github_result, access_token)
    user = User.try(:find_by_github_id, github_result.id)
    if user
      user.update(access_token: access_token)
    else
      user = User.create(user_params(github_result, access_token))
    end

    session[:id] = user.id
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  def languages
    @id = params[:id]
    repo = Repository.find(@id)

    if repo.languages.nil?
      languages = Recommender::Support::Repository.get_languages(current_user.access_token, repo.name)
      repo.languages = languages
      repo.save
    end

    @languages = repo.language_breakdown
    respond_to do |format|
      format.js
    end
  end

  def analyze_readme
    @keyword_score = Recommender::RecommenderActions.analyze_readme(current_user, params[:id])

    respond_to do |format|
      format.js
      format.json { render json: { score: @keyword_score } }
    end
  end

  def analyze_language
    @language_score = Recommender::RecommenderActions.analyze_language(current_user, params[:id])

    respond_to do |format|
      format.js
      format.json { render json: { score: @language_score } }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    if current_user.update(user_params)
      respond_to do |format|
        format.html
        format.js
        format.json { render json: current_user, status: 202 }
      end
    else
      render '/profile'
    end
  end

  def languages
    @languages = Recommender::OctokitActions.user_languages(current_user)
    current_user.update(language_breakdown: @languages)
    respond_to do |format|
      format.js
    end
  end

  def repositories
    @repositories = Recommender::OctokitActions.user_repos(current_user)

    respond_to do |format|
      format.js
    end
  end

  protected
  def user_params
    params.require(:user).permit(:keyword_one, :keyword_two,:keyword_three, :keyword_four, :keyword_five)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  ## GET
  # root url of the application
  def index
    @authorization_url = "https://github.com/login/oauth/authorize"
    @authorization_url += "?client_id=#{ENV["client_id"]}"
    @authorization_url += "&scope=#{ENV["scopes"]}"
    @authorization_url += "&state=#{ENV["state"]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def octicon(code, use_mega = false, extra_classes = nil)
    mega = use_mega ? "mega-" : ""
    content_tag :span, '', :class => "#{mega}octicon octicon-#{code.to_s.dasherize} #{extra_classes}"
  end

  def current_user
    true
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def repository_icon(repo)
    if repo.is_private
      octicon("lock", true)
    elsif repo.is_forked
      octicon("repo-forked", true)
    else
      octicon("repo", true)
    end
  end

  def repository_description(repo)
    repo.description || "No description given"
  end

  def favorability_string(score, max = nil)
    max ||= 200
    red = score.eql?(max) ? 220 : score
    green = score.eql?(max) ? 30 : 255 - score
    width = (max - score)/max.to_f * 100

    "background-color: rgb(#{red}, #{green}, 0); width: #{width}%; height: 25px;"
  end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/redirects_helper.rb
module RedirectsHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    User.find(session[:id])
  end

  def user_signed_in?
    !session[:id].nil?
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitRecommender</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row-fluid">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/profiles/_keywords.haml
= octicon("heart", nil, "keyword-heart heart-one")
= best_in_place current_user, :keyword_one, url: update_path, place_holder: "Top Keyword", class: "light keyword", html_attrs: { placeholder: "Enter Keyword", class: "form-control" }
%br
%br
= octicon("heart", nil, "keyword-heart heart-two")
= best_in_place current_user, :keyword_two, url: update_path, place_holder: "Next Keyword", class: "light keyword", html_attrs: { placeholder: "Enter Keyword", class: "form-control" }
%br
%br
= octicon("heart", nil, "keyword-heart heart-three")
= best_in_place current_user, :keyword_three, url: update_path, place_holder: "Next Keyword", class: "light keyword", html_attrs: { placeholder: "Enter Keyword", class: "form-control" }
%br
%br
= octicon("heart", nil, "keyword-heart heart-four")
= best_in_place current_user, :keyword_four, url: update_path, place_holder: "Next Keyword", class: "light keyword", html_attrs: { placeholder: "Enter Keyword", class: "form-control" }
%br
%br
= octicon("heart", nil, "keyword-heart heart-five")
= best_in_place current_user, :keyword_five, url: update_path, place_holder: "Bottom Keyword", class: "light keyword", html_attrs: { placeholder: "Enter Keyword", class: "form-control" }

app/views/profiles/show.haml
.col-md-9
  %h1.text-center Your Repositories
  %hr.margin-bottom
  #user-repositories-loading
    Loading your repository information
    .progress
      .progress-bar.progress-bar-striped.progress-bar-success.active.language-bar
  #user-repositories
.col-md-3.margin-bottom
  = image_tag(current_user.avatar_url, class: "img-rounded profile-picture")
  %button.btn.btn-warning.logout.btn-block Log Out
  %h3.light#user{ data: { user: current_user.github_id } }
    = octicon("person", true)
    = current_user.login
  %h4.light
    Language Breakdown
    %span.octicon.octicon-info{ data: { toggle: "tooltip", placement: "top", title: "Your usage of languages across your repositories." } }
  #user-languages-loading
    Calculating
    .progress
      .progress-bar.progress-bar-striped.progress-bar-success.active.language-bar
  #user-languages
  %h4.light
    Preferred Keywords
    %span.octicon.octicon-info{ data: { toggle: "tooltip", placement: "top", title: "Keywords boost the scores of repositories in which they are found." } }
  %p.light Choose 5 keywords in order of most desirable to least desirable.
  = render partial: "keywords"
#recommendations

app/views/recommendations/_recommendation_modal.erb
<div class="modal fade" id="recommendations-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Recommended Repositories</h4>
      </div>
      <div class="modal-body">
        <% @top_five.each do |result| %>
         <%= render partial: 'recommended_repository', locals: { repository: result, colors: colors } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recommendations/_recommended_repository.erb
<div class="col-md-12">
  <div class="col-md-6">
    <div class="repo-top">
      <%= repository_icon(repository[1]) %>
      <a class="repo-link.adhere-top" href="https://github.com/<%= repository[1].name %>">
        <%= repository[1].name %>
      </a>
    </div>
    <div class="col-md-4 legend" id="<%= repository[1].id %>-legend"></div>
    <div class="col-md-8 chart modal-chart"  id="repo-languages-<%= repository[1].id %>">
      <canvas id= "<%= repository[1].id %>-languages", width: "160px;", height: "144px;"></canvas>
    </div>
  </div>
  <div class="col-md-5">
    <h5 class="light">
      <%= octicon("calendar") %>
      Last Commit Date:
      <%= repository[1].pushed_at.strftime("%-m/%d/%Y") %>
    </h5>
    <h5 class="light">
      <%= octicon("star") %>
      Stars:
      <%= number_with_delimiter(repository[1].watchers, delimiter: ',') %>
    </h5>
    <h5 class="light">
      <%= octicon("book") %>
      <%= repository_description(repository[1]) %>
    </h5>
    <br/>
    <h4 class="light" id="score-<%= repository[1].id %>" >
      Favorability
    </h4>
    <h4>
      <p style="<%= favorability_string(repository[0].to_i) %>"></p>
    </h4>
  </div>
</div>
<div class="col-md-8">
  <hr class="repo-row"/>

</div>

app/views/recommendations/recommend.js.erb
<% colors = JSON.parse(File.read("vendor/assets/json/colors.json")) %>

$('#recommendations').html("<%= escape_javascript render partial: 'recommendation_modal', locals: { colors: colors } %>")
$('#recommendations-modal').modal('toggle');
$('#recommendations-modal').on('shown.bs.modal', function (event) {
  <% @top_five.each do |repository| %>
    <% if !repository[1].languages.empty? %>
      data<%= repository[1].id %> = [
        <% repository[1].language_breakdown.each do |language| %>
          {
            value: "<%= language[1] %>",
            color: "<%= colors[language[0]] %>",
            highlight: "<%= colors[language[0]] %>",
            label: "<%= language[0] %>",
          },
        <% end %>
      ];

      legendString = "<ul class='doughnut-legend'>";
      <% repository[1].languages.each do |language, value| %>
        legendString += "<li style='font-weight:200; padding: 5px;'>";
        legendString += "<span style='background-color: <%= colors[language.to_s] %>; color: rgba(255, 0, 0, 0); margin-right: 3px;'>";
        legendString += "X";
        legendString += "</span>";
        legendString += "<%= language.to_s %>";
        legendString += "</li>";
      <% end %>
      legendString += "</ul>";

      options = {
        legendTemplate: legendString
      };
      $('#<%= repository[1].id %>-legend').html(legendString);
      myNewChart<%= repository[1].id %> = new Chart($('#<%= repository[1].id %>-languages').get(0).getContext("2d")).Doughnut(data<%= repository[1].id %>);
      legendString = "";
    <% else %>
      $('#<%= repository[1].id %>-legend').remove();
      $('#repo-languages-<%= repository[1].id %>').removeClass("col-md-4 modal-chart");
      $('#repo-languages-<%= repository[1].id %>').addClass("col-md-8")
      $('#repo-languages-<%= repository[1].id %>').html("<h5 class='light'>No language information available for this repository.</h5>");
    <% end %>
  <% end %>
});
$('#recommend-button').removeClass('disabled');
$('#recommend-progress').css('display', 'none');

app/views/redirects/error.haml
%h1 ERROR

app/views/redirects/handle.haml
%h1 HANDLED

app/views/repositories/_repo_languages.haml
%canvas.repo-languages-chart{ id: id, width: "200px", height: "180px" }

app/views/repositories/analyze_language.js.erb
$("#score-<%= params[:id] %>").data("language", <%= @language_score %>);
totalScore = ($("#score-<%= params[:id] %>").data().keyword + <%= @language_score %>)
red = parseInt(totalScore);
green = parseInt(255 - totalScore);

if(parseInt(totalScore) === 200) {
  red = 220;
  green = 30;
}

width = ((200 - totalScore)/200.0) * 100;

styleString = "background-color: rgb(" + red + ", " + green + ", 0); width: " + width + "%; height:25px;"

$("#score-<%= params[:id] %>").html("Favorability");
$('#score-<%= params[:id] %>').after("<h4><p style='" + styleString + "'></h4>");

app/views/repositories/analyze_readme.js.erb
$("#score-<%= params[:id] %>").data("keyword", <%= @keyword_score %>);
$.ajax("/repositories/<%= params[:id] %>/language")

app/views/repositories/languages.js.erb
<% if !@languages.empty? %>
  $('#repo-languages-<%= @id %>').html("<%= escape_javascript(render partial: 'repo_languages', locals: { id: @id } ) %>");
  <% colors = JSON.parse(File.read("vendor/assets/json/colors.json")) %>
  data = [
    <% @languages.each do |language, value| %>
      {
        value: <%= value %>,
        color: "<%= colors[language.to_s] %>",
        highlight: "<%= colors[language.to_s] %>",
        label: "<%= language %>"
      },
    <% end %>
  ];

  legendString = "<ul class='doughnut-legend'>";
  <% @languages.each do |language, value| %>
    legendString += "<li style='font-weight:200; padding: 5px;'>";
    legendString += "<span style='background-color: <%= colors[language.to_s] %>; color: rgba(255, 0, 0, 0); margin-right: 3px;'>";
    legendString += "X";
    legendString += "</span>";
    legendString += "<%= language.to_s %>";
    legendString += "</li>";
  <% end %>
  legendString += "</ul>";

  options = {
    legendTemplate: legendString
  };

  myNewChart = new Chart($('#<%= @id %>').get(0).getContext("2d")).Doughnut(data, options);
  $('#<%= @id %>-legend').html(legendString);
<% else %>
$('#<%= @id %>-legend').remove();
$('#repo-languages-<%= @id %>').toggleClass("col-md-4 col-md-8");
$('#repo-languages-<%= @id %>').html("<h5 class='light'>No language information available for this repository.</h5>");
<% end %>

<% if current_user.has_all_keywords? %>
  $.ajax("/repositories/<%= @id %>/readme");
<% else %>
  $('#score-<%= @id %>').html("Choose 5 keywords then refresh the page in order to score this repository.")
<% end %>

app/views/users/_repository.haml
.col-md-12
  .col-md-6
    %div.repo-top
      = repository_icon(repository)
      %a.repo-link.adhere-top{ href: "https://github.com/#{repository.name}" }
        = repository.name

    .col-md-4.legend{ id: "#{repository.id}-legend"}
    .col-md-4.chart{ id: "repo-languages-#{repository.id}" }
      %div
        Calculating Languages
        .progress
          .progress-bar.progress-bar-striped.progress-bar-success.active.language-bar
        :javascript
          $.ajax("repositories/#{repository.id}/languages");
  .col-md-5
    %h5.light
      = octicon("calendar")
      Last Commit Date:
      = repository.pushed_at.strftime("%-m/%d/%Y")
    %h5.light
      = octicon("star")
      Stars:
      = number_with_delimiter(repository.watchers, delimiter: ',')
    %h5.light
      = octicon("book")
      = repository_description(repository)
    %br
    %h4.light{ id: "score-#{repository.id}" }
      Calculating The Score
      .progress
        .progress-bar.progress-bar-striped.progress-bar-success.active.language-bar
.col-md-8
  %hr.repo-row

app/views/users/_user_languages.haml
%canvas#user-languages-chart{ width: "220px;", height: "200px;" }

app/views/users/languages.js.erb
$('#user-languages').html("<%= escape_javascript(render partial: 'user_languages' ) %>");
$('#user-languages-loading').remove();
<% colors = JSON.parse(File.read("vendor/assets/json/colors.json")) %>
data = [
  <% @languages.each do |language| %>
    {
      value: <%= language[1] %>,
      color: "<%= colors[language[0]] %>",
      highlight: "<%= colors[language[0]] %>",
      label: "<%= language[0] %>"
    },
  <% end %>
];
myNewChart = new Chart($('#user-languages-chart').get(0).getContext("2d")).Doughnut(data);

app/views/users/repositories.js.erb
$('#user-repositories').append('<div id="recommend-progress" class="progress"><div class="progress-bar progress-bar-striped progress-bar-info active language-bar"></div></div><%= link_to "Recommend Me Repositories", recommend_path, id: "recommend-button", class: "recommend-btn btn btn-success btn-large btn-block", remote: true %>');
$('#recommend-button').on('click', function()
  { $('#recommend-button').addClass('disabled');
  $('#recommend-progress').css('display', 'block');
});
<% @repositories.each do |repo| %>
  $('#user-repositories').append("<%= escape_javascript(render partial: 'repository', locals: { repository: repo }) %>")
<% end %>
$('#user-repositories-loading').remove();

app/views/welcome/index.haml
.col-md-12
  .col-md-6.col-md-offset-3
    %h1.text-center
      Welcome to GitRecommender
      = octicon("mark-github", true)
      %hr
  .col-md-10.col-md-offset-1.margin-bottom
    %h2.text-center.margin-bottom
      The Process
    .col-md-3.text-center
      %span.glyphicon.glyphicon-user.welcome-icon
      %br
      %h5 Give us your GitHub username
    .col-md-3.text-center
      %span.glyphicon.glyphicon-console.welcome-icon
      %br
      %h5 Specify some keywords
    .col-md-3.text-center
      = octicon("repo", true, "welcome-octicon")
      %br
      %h5 Receive a list of repos
    .col-md-3.text-center
      = octicon("heart", true, "welcome-octicon")
      %br
      %h5 Enjoy the recommendations
  .col-md-4.col-md-offset-4
    = link_to "Get Started", @authorization_url, class: "btn btn-success btn-large btn-block"